# Generated by Django 4.1.3 on 2024-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='devise',
            field=models.CharField(blank=True, choices=[('Fcfa', 'F'), ('dollar', '$')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
