# Generated by Django 4.1.3 on 2024-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='devise',
            field=models.CharField(blank=True, choices=[('euro', 'Є'), ('vientam dong', 'VND')], max_length=255, null=True),
        ),
    ]
