# Generated by Django 4.1.3 on 2024-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharma_app", "0003_alter_article_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="quantite_en_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
