# Generated by Django 4.1.3 on 2024-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharma_app", "0004_article_quantite_en_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="panier",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
