# Generated by Django 4.1.3 on 2024-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharma_app", "0006_commande_sub_total_commande_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="nbr_article",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
