# Generated by Django 4.1.3 on 2024-11-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharma_app", "0008_detail_commande_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail_commande",
            name="price",
        ),
    ]
