# Generated by Django 4.1.3 on 2024-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndk_app', '0015_commande_adresse_commande_code_postal_commande_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='etiquette',
            field=models.ManyToManyField(to='ndk_app.etiquette'),
        ),
    ]
